### ISSUE TITLE
怎么只返回了群号

### ISSUE THREAD

**Issue by Admsec** [Jerry080801/nonebot-plugin-antirecall#1]
![image](https://user-images.githubusercontent.com/86643414/208840392-0837be57-6bc3-4576-8c40-605a0ffe0021.png)

**Comment by Jerry080801** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/105533056/208843604-9f523a6b-7527-4849-802d-4c15b0f8a10d.png">

**Comment by Jerry080801** [comment]
啊?我返回的是“你干嘛”啊

**Comment by Admsec** [comment]
我用的是nonebot_gocqhttp插件，不是用的本体，不知道是不是这里的问题；
我还测试了一下，就是到最后一步发送信息那里它死都不执行，奇奇怪怪的

**Comment by Admsec** [comment]
我现在还在测试

**Comment by Jerry080801** [comment]
我觉得有可能是适配啥的问题?

**Comment by Admsec** [comment]
似乎是在最后一句 if 判断那里的问题，我把语句放在 if 上面就没问题了

**Comment by Admsec** [comment]
最后那个 if 那里那个 gid 是整型
![image](https://user-images.githubusercontent.com/86643414/208849030-8b6c472b-9c98-425d-a7b5-bb2e71306b48.png)
