### ISSUE TITLE
[BUG]: ValueError ?

### ISSUE THREAD

**Issue by zhulinyv** [Jerry080801/nonebot-plugin-antirecall#2]
功能可以正常使用，但出现以下报错 :(

![5b77d4ce0051e74b.jpg](https://s2.loli.net/2022/12/21/nxYEuhLj4e17srQ.jpg)

**Comment by Jerry080801** [comment]
恼.我咋没遇到过

**Comment by zhulinyv** [comment]
> 恼.我咋没遇到过

我不确定发生了什么，但在自己电脑上是没问题的QwQ
![image](https://user-images.githubusercontent.com/66541860/209078105-2f33fb73-be11-4253-9394-e1d02abd1ac8.png)

**Comment by Jerry080801** [comment]
嗯我会继续观察的,这是我第一个project人很菜.
