### ISSUE TITLE
关于撤回的建议

### ISSUE THREAD

**Issue by YouYouLip** [Jerry080801/nonebot-plugin-antirecall#3]
撤回消息可不可以额外加一个私信给超级用户 收到了来自己群号+qq号或者ID的撤回消息

**Comment by Jerry080801** [comment]
好的,现在写哈哈哈
疫情停课在家

**Comment by Jerry080801** [comment]
私聊老是封控,我弄了一个类似的功能,拉一个群

**Comment by YouYouLip** [comment]
> 私聊老是封控,我弄了一个类似的功能,拉一个群

嗯嗯 感谢考虑 说起来 风控这个只限没有添加bot为好友才会触发的吧（疑惑）而且作者您的插件还会和nonebot商店插件中kawaii_robot这个插件的戳一戳回复冲突 就是安装上您的插件他这个戳一戳功能回复会消失（doge）虽然我现在打算换一个自定义词库了 不过还是有可能同时用这2个功能的人最好还是尝试修一下吧

**Comment by Jerry080801** [comment]
好像是因为on_notice我设置了block, 我删了block了,应该不会冲突了

**Comment by YouYouLip** [comment]
> 好像是因为on_notice我设置了block， 我删了block了，应该不会冲突了

感谢修复 辛苦了
